### ISSUE TITLE
Gracefully drop geographies that aren't available

### ISSUE THREAD

**Issue by dylan-knaggs** [socrata/autocensus#9]
Currently, we get a BadZipFile error if trying to get data for a year where it isn't available per https://www.census.gov/geographies/mapping-files/time-series/geo/carto-boundary-file.html. We should gracefully drop these geographies if that is the case. 

Per slack conversation with @cmsetzer 

>  ideally autocensus would gracefully not try to download/join a shapefile if it doesn't exist. could probably fix this by checking the  response status code in fetch_geography https://github.com/socrata/autocensus/blob/master/autocensus/api.py#L145
> 
> then, probably have to filter out Nones or something in https://github.com/socrata/autocensus/blob/master/autocensus/query.py#L262-L270

**Comment by cmsetzer** [comment]
I believe I've fixed this in https://github.com/socrata/autocensus/commit/3f89db6072f477f687b190591c28ec124ba58050, released just now in [v1.0.7](https://github.com/socrata/autocensus/releases/tag/v1.0.7).

autocensus now:
* Provides informative warning and does not download shapefile when it receives a non-200 response from Census
* Provides informative warning and does not join shapefile when it gets a `BadZipFile` error (typically due to incompletely downloaded shapefile, etc.)

Thanks for posting this.
